on:
  schedule:
    - cron: "0 0 * * 0"

name: rebuild

jobs:
  rebuild:
    name: "sundries"
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Bumping the date
        run: |
            curdate=$(date --rfc-3339=date)
            cat Dockerfile | sed "s/date=\".*\"/date=\"${curdate}\"/" > tmp
            mv tmp Dockerfile
      - name: Committing to master
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Dockerfile
          git commit -m "Bumping the Dockerfile date." || true
          git push
